import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "mapbox-gl/dist/mapbox-gl.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AirBnB Clone App",
  description: "Generated by mksamuel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#FE595E" height={8} />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
